#!/bin/bash
# maparrar@gmail.com
# https://github.com/maparrar/bluetooth-problem
# 2018-01-07

gksu -- bash -c '
sudo pip install pyusb;
sudo modprobe -r btusb;
sudo modprobe btusb;
sleep 2;
sudo python $HOME/path/tools/bluetooth-problem/bt.py;
sudo python $HOME/path/tools/bluetooth-problem/bt.py;'
